name: CI-Polaris
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest]
    env:
      MAC_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-action/0.1.72/ci-package-0.1.72-macosx.zip"
      LINUX_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-action/0.1.72/ci-package-0.1.72-linux64.zip"
      WINDOWS_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-action/0.1.72/ci-package-0.1.72-win64.zip"
    steps:
      - uses: actions/checkout@v3
      - name: Use synopsys unified-action
        uses: synopsys-sig/synopsys-action@v0.1.0
        with:
          #blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          #blackduck_apiToken: "MDQxNjNjMTAtMGY4NS00YmMzLTgyOTMtYmM5ZTYwM2E5NTY1OjkzYmExMThiLTdmOTctNDk4ZS04ZGU0LTNhNmJlYmM0MWM5OA=="
          #blackduck_scan_full: true
          #blackduck_install_directory: /home/runner/synopsys-bridge/
          #blackduck_scan_failure_severities: "[\"ALL\"]"
          bridge_download_url: ${{ env.LINUX_BRIDGE_URL }}

          # coverity changes
          #coverity_url: ${{ secrets.COVERITY_URL }}
          #coverity_user: ${{ secrets.COVERITY_USER }}
          #coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          #coverity_project_name: ${{ secrets.COVERITY_PROJECT_NAME }}
          #coverity_stream_name: ${{ secrets.COVERITY_STREAM_NAME }}
          #coverity_policy_view: ${{ secrets.COVERITY_POLICY_VIEW }}
          #coverity_repository_name: "test_action"
          #coverity_branch_name: "main"
          # Mandatory for windows hosted environment
          #coverity_install_directory: "/root"

          #polaris
          #polaris_serverUrl: "https://cdev.altair.synopsys.com/"
          #polaris_accessToken: "816smiaag16kl3p6e6417e0cr4aoi6s747nkdus8e4g5n5te46bsrkku6hatr7majpninibea6vm0"
          polaris_serverUrl: "https://polaris.synopsys.com/"
          polaris_accessToken: "t8mj38ii950jn1brrl9qhqg8no8qcj1db6dknls4qgqf35l5206qbhq2ecs1a5v0fp764dd4pkvgo"
          polaris_application_name: "tb_app1"
          polaris_project_name: "tb_proj"
          polaris_assessment_types: "[ \"SCA\" ]"
