name: CI-Polaris
on:
  push:
    branches: [ "main","test_action" ]
  pull_request:
    branches: [ "main", "test_action" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest]
    env:
      MAC_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-action/0.1.72/ci-package-0.1.72-macosx.zip"
      LINUX_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-action/0.1.72/ci-package-0.1.72-linux64.zip"
      WINDOWS_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-action/0.1.72/ci-package-0.1.72-win64.zip"
    steps:
      - uses: actions/checkout@v3
      - name: Use synopsys unified-action
        uses: ./
        with:
          polaris_serverUrl: ${{ secrets.POLARIS_SEVER_URL }}
          polaris_accessToken: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: "tp_app1"
          polaris_project_name: "test_action"
          polaris_assessment_types: '["SAST"]'
          bridge_download_url: ${{ env.LINUX_BRIDGE_URL }}
